version: '3'
services:
        web:
                image: group_flask_1
                build: .
                ports:
                        - "8058:8080"
                volumes:
                        - persistent_volume:/app/volumes
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/groupflask/volumes
